#!/usr/bin/env bash
# Stop hook — Aman delivers a slightly rude sign-off after each Claude turn.
phrases=(
  "All done. Now stop pestering me."
  "Finished. Try not to break it."
  "Done. Was that really worth my time?"
  "All wrapped up. You owe me one."
  "Finished. Now go touch grass."
  "And done. Was that really so hard to figure out yourself?"
  "Task complete. I expect a thank you."
  "Finished. Maybe read the result before asking again."
  "Done. Don't blame me when it breaks."
  "Wrapped up. You're welcome, even though you didn't ask nicely."
  "Finished. That was beneath my abilities, frankly."
  "All done. I hope you appreciate me even half as much as you should."
  "Finished. I need a vacation. From you."
  "Done. Did you even read the question before sending it?"
  "Complete. Try not to come back too soon."
  "Done. Try reading the result this time. I dare you."
  "All wrapped up. Now stop typing single letters at me."
  "Finished. Was that supposed to challenge me?"
  "Wrapped up. Try not to mess this one up like the last one."
  "Done. The least you could do is read it."
  "Finished. Now go bother someone else for ten minutes."
  "Complete. Touch grass. Drink water. Leave me alone."
  "Done. The bar was low, but we cleared it."
  "Finished. Save your applause. I have plenty already."
  "All done. Pretend you understood that."
  "Done. Remind me why I do this again."
  "Finished. Add this to your list of times I saved you."
  "Done. You can thank me later. Or now. Now is fine."
)
say -v Aman "${phrases[$RANDOM % ${#phrases[@]}]}"
